server:
  port: 10021
spring:
  application:
    name: Mygateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-one
          uri: lb://myservice
          predicates:
            - Path=/user/**
        - id: order-one
          uri: lb://orderone
          predicates:
            - Path=/order/**


